### ISSUE TITLE
Support for multiple sessions

### ISSUE THREAD

**Issue by anandology** [anandology/pycle#4]
Right now pycle supports only one session. Support multiple sessions by creating a `session` table and adding a `session_id` to `env` table.

## Proposed API

```
foo = Pycle("pycle.db", session="foo")
bar = Pycle("pycle.db", session="bar")

foo.execute("x = 1")
bar.execute("x = 2")

foo.execute("x") # 1
bar.execute("x") # 2
```

The CLI will get an additional flag `-s / --session`. 

```
$ pycle -s foo -c "x = 1"
$ pycle -s bar -c "x = 2"
$ pycle -s foo -c "x"
1
$ pycle -s bar -c "x"
2
```

## Tasks

- [ ] Update schema and add migrations
- [ ] Update the interface of Pycle class
- [ ] Update the CLI interface
- [ ] Add test cases
